Changes for documentations
dajmcdon/sparsegl pull request #9
Opened 2021-06-16 22:27 UTC by Xiaoxuan1121

Might need a link for 'glmtnet-package' in functions cv.sparsegl() and plot.cv.sparsegl().

2021-06-21 22:06 UTC, dajmcdon requested changes

2021-06-21 22:06 UTC, dajmcdon commented on R/norms.R
> +# Returns L^1-norm (Absolute-value norm).
For all of these, can you add the Roxygen and export? Let's document them all together. See [here](https://r-pkgs.org/man.html#multiple-man).

2021-06-21 22:06 UTC, dajmcdon commented on R/plot.cv.sparsegl.R
> +#' @param \dots Other graphical parameters to plot
I think \dots is ignored. Is it? If so, please say so.

2021-06-21 22:06 UTC, dajmcdon commented on R/plot.sparsegl.R
> +#' @param \dots Other graphical parameters to plot.
Same as on `plot.cv.sparsegl`

2021-06-21 22:06 UTC, dajmcdon commented on _pkgdown.yml
> +    - predict.cv.sparsegl
replace with
 - starts_with(plot)
 - starts_with(predict)
 - starts_with(print)
 - starts_with(coef)

2021-06-21 22:16 UTC, Xiaoxuan1121 commented
Sure! I'll fix them up before making another PR!

2021-06-30 14:24 UTC, dajmcdon requested changes

2021-06-30 14:24 UTC, dajmcdon commented on R/norms.R
> +#' @describeIn grouped_sp_norm l1-norm (Absolute-value norm).
All of these need to be exported.

2021-07-05 18:48 UTC, dajmcdon approved these changes

2021-07-05 18:48 UTC, merged